### ISSUE TITLE
🛠️ [TASK] : Update chromium installer to install packages matching major version

### ISSUE THREAD

**Issue by dtscalac** [input-output-hk/catalyst-ci#279]
### Summary

Update chromium installer to install packages matching major version

### Description

Update [chromium installer](https://github.com/input-output-hk/catalyst-ci/blob/master/earthly/flutter/installer/Earthfile) to install any chromium package that matches a major version. 

Currently chromium installer requires a very specific version that is downloaded using curl from a debian repository.
Apparently the debian repository keeps removing older versions and adds new ones thus the package we're trying to get doesn't exist but a new one with very similar version is available.

I.e. this package `126.0.6478.56-1~deb12u1` existed but it was replaced by `126.0.6478.126-1~deb12u1` version and the installer was failing because it depended specifically on `126.0.6478.56-1~deb12u1`. The goal is to install any 126.x.x.x version that is available on the repository so that package removals don't affect the CI. The major version should be configurable as target argument.

Note:
_Consider to create a reusable tool that can install other packages, the tool should only respect the major version or provide a configuration to pass a regular expression to filter supported package versions._

**Comment by stevenj** [comment]
Yes, what we need is a smart curl replacement.
It is provided a URL to files, and a glob pattern for the file wanted, it finds the largest canonically sorted file that matches the pattern and downloads it, renaming it to a given generic name.

Something like:
```
dl_from.py <url> "google-chrome-109.*.tar.gz" google-chrome.tar.gz
```
