### ISSUE TITLE
[Feature]: We need to get GITHUB_TOKEn into Earthly CI runs.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-ci#296]
### Feature Title

Add GITHUB_TOKEN to Earthly runs

### Feature Description

We need GITHUB_TOKEN to run cargo binstall which is necessary for the new rust builders.
As the new chain follower code and cat-gateway will need this version, its blocking Milestone 3, and all my CI runs in these repos fail early and fast.

This is a very high priority issue as it's blocking milestone 3.

### Use Case

executing `cargo binstall` in the rust builders.

### Is this a modification to an existing feature?

Yes

**Comment by jmgilman** [comment]
Done via #297 and #300. All Earthly executions now get a secret passed call `GITHUB_TOKEN`. It can be used like:

```
RUN --secret GITHUB_TOKEN=GITHUB_TOKEN echo "Do something with it"
```

 I updated your original PR, but it's failing with a build issue related to dbviz.
