### ISSUE TITLE
Refactor the CI process to include build and integration steps

### ISSUE THREAD

**Issue by jmgilman** [input-output-hk/catalyst-ci#51]
```mermaid
flowchart TD
    A[Check] --> B[Build] --> C[Integrate]
    C --> D[Release]
    C --> E[Publish]
```

This solves a few problems:

1. The `release` and `publish` targets naturally depend on the `build` target. However, not defining the `build` target as an explicit CI step means that it's likely to get executed twice when the `release`/`publish` targets get run in parallel. Making `build` a recognized target prevents this. 
2. It's currently possible to build/release artifacts with failing integration tests (as they originally fell outside of the CI process). Adding a formal `integrate` target and making the `build`/`publish` targets dependent on it will solve this. 

The `integrate` target _does not_ need to be present in every Earthfile. It's likely we'll have them contained in a separate Earthfile. To the CI, it doesn't matter because it searches the whole repo for the target anyways.

**Comment by stevenj** [comment]
LGTM.  This should give us a great amount of flexibility, and allow us to build a heterogeneous monorepo in a sensible way.

**Comment by jmgilman** [comment]
The implementation is done. Documenting it will be done in #50.
