### ISSUE TITLE
Disable TCP Keepalive for SSH to hetzner machine.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-ci#85]
The mainnet snapshot on the Hetzner machine is timing out with client_loop: send disconnect: Broken pipe 

REF:
https://unix.stackexchange.com/questions/602518/ssh-connection-client-loop-send-disconnect-broken-pipe-or-connection-reset
https://unix.stackexchange.com/questions/34004/how-does-tcp-keepalive-work-in-ssh

**Comment by FelipeRosa** [comment]
Closed by https://github.com/input-output-hk/catalyst-core/pull/630
